### ISSUE TITLE
Is get_objectData(msg) general enough?

### ISSUE THREAD

**Issue by dwright04** [rafia17/Zooniverse_SLSN#1]
### Context
get_objectData(msg) - msg is a message polled from a kafka topic. 

This method parses the method to extract an objectname then wgets the lasair json blob for this that object.

### Question
Do we foresee a case where a user might want to parse the message for some other information other than objectname and perform some other action?

### Implications
If true, then we want user-definable parsing and actions.

**Comment by rafia17** [comment]
Hi Darryl,

As of now, this method (as the name itself suggests) is very specific and parses the msg from kafka stream looking specifically for the string "objectId". Then it wgets the data for the objectId. An objectId would of course be the key to getting object data.

Here's what a msg looks like:
{"objectId": "ZTF20aalkxvg", "mjdnow": 58898.194722222164, "mjdmin": 58879.17971060006, "mjdmax": 58898.15491899988, "magrmin": 19.3276, "latestrmag": 19.3374, "classification": "NT", "score": "Not Near PS1 star", "UTC": "2020-02-19 04:40:40"}

If the user wants some other data at the object level, we might want to implement a generic method like get_fieldFromKafkaMsg(fieldname).

**Comment by dwright04** [comment]
Thanks Rafia,

this is helpful.  Yes, something like get_fieldFromKafkaMsg(fieldname) would be the solution if it is needed.

However, based on the example msg you provided I don't foresee a case where we would use this message for anything else other than retrieving object data.

Let's continue assuming this is true.  I'll close this for now and we can reopen if this assumption is too strong.
