### ISSUE TITLE
make_scatter_plot needs refactored to separate data parsing from plotting

### ISSUE THREAD

**Issue by dwright04** [rafia17/Zooniverse_SLSN#2]
### Context

The make_scatter_plot method currently takes an objectID that identifies a downloaded json file containing the lightcurve data for an object.  The method then plots this data.

### Problem
Data parsing and plotting will eventually be two methods that must inherit from abstract base classes.  We should isolate user-configurable components.

### Steps to resolve
1. Define abstract base class for data parsing
2. Define abstract base class for plotting
3. Define SLSN project specific data parsing method/class
4. Define SLSN project specific plotting method/class

**Comment by rafia17** [comment]
Yes, I agree. I think we discussed restructuring the code yesterday. Right now, the way its done has simply tested different functionalities if they are working or not. 
I will be restructuring the code making abstract base classes and then following the flow-chart in the document that you shared.

**Comment by dwright04** [comment]
Closing this issue.

Data parsing performed by:
https://github.com/rafia17/Zooniverse_SLSN/blob/062945eeb56a943bb535af34a15adebeab2d2313/lasair_zooniverse.py#L121

Plotting performed by:
https://github.com/rafia17/Zooniverse_SLSN/blob/062945eeb56a943bb535af34a15adebeab2d2313/lasair_zooniverse.py#L160
