### ISSUE TITLE
panstamps arcsecSize 

### ISSUE THREAD

**Issue by dwright04** [rafia17/Zooniverse_SLSN#8]
https://github.com/rafia17/Zooniverse_SLSN/blob/062945eeb56a943bb535af34a15adebeab2d2313/lasair_zooniverse.py#L204

I think the default arcsecSize for panstamps should be 300.  This size is used here for example:

https://star.pst.qub.ac.uk/ps1threepi/psdb/public_quickview/

and seems to work well for identifying the host.

**Comment by rafia17** [comment]
Resolved

**Comment by dwright04** [comment]
The arcsecSize still seems to default to 500 arcsecs.   Either way, I made a mistake when I opened this issue.  I think we want the panstamps images to be 300x300 pixels, not 300x300 arcsecs.  Each pixel for PS1 subtends ~0.25 arcsecs so we want to request images from panstamps that are 75x75 arcsecs (300*0.25).  

arcsecSize should be set to 75.

**Comment by dwright04** [comment]
Closing as this is resolved by:

https://github.com/rafia17/Zooniverse_SLSN/blob/e9c9969606bdf8baa1332f3cb97317852648a68e/lasair_zooniverse.py#L180
