### ISSUE TITLE
create_subjects_and_link_to_project should be a method of the lasair_zooniverse_base_class

### ISSUE THREAD

**Issue by dwright04** [rafia17/Zooniverse_SLSN#9]
https://github.com/rafia17/Zooniverse_SLSN/blob/062945eeb56a943bb535af34a15adebeab2d2313/lasair_zooniverse.py#L89
The `create_subjects_and_link_to_project` should be inherited from the `lasair_zooniverse_base_class`.  Users of this codebase should only need to design their plots and gather metadata.  Interaction with panoptes should be hidden.

**Comment by rafia17** [comment]
Resolved
